# Generated by Django 5.2.4 on 2025-07-10 03:48

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=200, null=True)),
                ('categoryImage', models.ImageField(blank=True, null=True, upload_to='images/Categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('customerPhone', models.CharField(max_length=20)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QRCodeInvoice', models.ImageField(blank=True, null=True, upload_to='images/QRCodeInvoice/')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrName', models.CharField(max_length=100)),
                ('qrImage', models.ImageField(upload_to='images/qrcodes/')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('productDescript', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('weight', models.CharField(max_length=200, null=True)),
                ('availability', models.CharField(max_length=200, null=True)),
                ('shipping', models.CharField(max_length=200, null=True)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='images/Products/')),
                ('productDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('categoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productDetailName', models.CharField(max_length=200, null=True)),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('Information', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('Reviews', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('productDetailDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productDetailImageName', models.CharField(max_length=200, null=True)),
                ('productDetailImage', models.ImageField(blank=True, null=True, upload_to='images/productDetail/')),
                ('imageDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
